# Generated by Django 4.2.7 on 2025-07-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Produto')),
                ('tipo_espectro', models.CharField(choices=[('sativa', 'Sativa'), ('indica', 'Indica'), ('hibrida', 'Híbrida')], max_length=10, verbose_name='Tipo de Espectro')),
                ('thc_percentual', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Percentual de THC (%)')),
                ('cbd_percentual', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Percentual de CBD (%)')),
                ('categoria_terapeutica', models.CharField(choices=[('neurologia', 'Neurologia'), ('pediatria', 'Pediatria'), ('oncologia', 'Oncologia'), ('dermatologia', 'Dermatologia'), ('outros', 'Outros')], max_length=20, verbose_name='Categoria Terapêutica')),
                ('status_anvisa', models.CharField(choices=[('aprovado', 'Aprovado'), ('pendente', 'Pendente'), ('reprovado', 'Reprovado')], default='pendente', max_length=10, verbose_name='Status ANVISA')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
